# Generated by Django 3.2.8 on 2023-05-15 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('valor_facial', models.CharField(max_length=45)),
                ('precio_avaluado', models.IntegerField()),
                ('ceca', models.CharField(max_length=45)),
                ('material', models.CharField(max_length=45)),
                ('peso', models.FloatField()),
                ('diametro', models.FloatField()),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('tipo_articulo', models.CharField(max_length=45)),
            ],
        ),
    ]
