# Generated by Django 4.2.1 on 2023-05-23 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_piezas', models.IntegerField()),
                ('fecha_inicio_coleccion', models.DateField()),
                ('estado_conservacion', models.CharField(choices=[('OPCION1', 'Mala'), ('OPCION2', 'Buena'), ('OPCION3', 'Regular'), ('OPCION4', 'Excelente')], max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coleccionista',
            fields=[
                ('identificacion', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('fecha_registro', models.DateField()),
                ('numero_tarjeta_bancaria', models.CharField(max_length=45)),
                ('tipo_cuenta', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('valor_facial', models.CharField(max_length=45)),
                ('precio_avaluado', models.IntegerField()),
                ('ceca', models.CharField(max_length=45, null=True)),
                ('material', models.CharField(max_length=45, null=True)),
                ('peso', models.FloatField()),
                ('diametro', models.FloatField(null=True)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('tipo_articulo', models.CharField(choices=[('Moneda', 'Moneda'), ('Billete', 'Billete')], max_length=45)),
                ('id_coleccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piezas.coleccion')),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('valor_compra', models.IntegerField()),
                ('id_coleccionista', models.CharField(max_length=45)),
                ('id_vendedor', models.CharField(max_length=45)),
                ('id_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piezas.pieza')),
            ],
        ),
        migrations.AddField(
            model_name='coleccion',
            name='identificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piezas.coleccionista', unique=True),
        ),
    ]
