# Generated by Django 4.2.1 on 2023-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='id_coleccion',
            field=models.CharField(max_length=45),
        ),
    ]
