# Generated by Django 4.2.1 on 2023-05-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_alter_pieza_id_coleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='coleccionista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piezas.coleccionista'),
            preserve_default=False,
        ),
    ]
