# Generated by Django 4.2.1 on 2023-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0003_pieza_coleccionista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_pieza',
            field=models.IntegerField(),
        ),
    ]
