# Generated by Django 4.1.9 on 2023-05-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0004_alter_compra_id_pieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_venta',
            field=models.CharField(max_length=45),
        ),
    ]
