# Generated by Django 4.1.9 on 2023-05-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0005_alter_compra_fecha_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coleccion',
        ),
    ]
